apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: tailscale-secrets
  namespace: tailscale
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHdlMHp3MW93c014QUV1
        UUxlTTUvelF5VlA4TC9FRlRYRWlFUkdZTUdJCmRheUZZZzNLZWs0NHZlbTNGcGU1
        YVFtcENZUEZDVTB3d2FpbllaWXorQm8KLS0tIE82c0hsZ0R4TDVVRnMvUSszQzk5
        a0tOUk5TdjRhRmtBQ0dCRnRIYVk2Sm8KSMBQIqYgoFkG1WQJGZ2/o3GnKY6g4QS0
        y0JYmlnQoECJn830jfTaZUT0NV6av5P2Gx6R7jEDnunPDQK79Xew+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjhzUkd5VVZxUXRyeFky
        NEM5NUJXYXJNQkRoSHJwMkw4aGk3MGtBZ0FrCmVYYi9vRndFN2R3ZkUrMzdJaWVm
        Wjd4dDd1eFdRMzdCZS83ajF5Y1JoV2sKLS0tIHIwNnpFbnhGRHJXN1hKT2lxOE9I
        czhtbFVJSDFRSzd5emRBc1dyY0k2eFkKUrKcQk2ObJqIem19q9DgtRcmXO6PLbSv
        7ixx9QqS2dqKVnd/o0QE2GvxmQXxujFwar/2HsTrH6ECpS1NU5Bp8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: "2025-02-02T19:27:36Z"
  mac: ENC[AES256_GCM,data:weWpLvg1pRa238mfoxxiYgTvvkw0guF3UtFRE8/AfM/s3DhoSVZBu/Ga8KwAfvW3c+1joYPQ+WlmaQFa0VRhVvgsez03E0Q7xSs3BFds6pZErKImUhKd0Lt8rfvVmGNCdn5cg7/37pI14w1QFVmL9O49hWWx3uNc4XGqr7yzWws=,iv:CrFXTUDv/xZ5z0NZGMB4GCyncvb4yQSYf2sDF+6iTsk=,tag:QjheR4t5hqb5gg0EhWIcPw==,type:str]
  pgp: []
  version: 3.9.4
spec:
  secretTemplates:
    - name: operator-oauth
      stringData:
        client_id: ENC[AES256_GCM,data:Hk7bS3OYMa11ef09nFf1buQ=,iv:UzfiJAoM6WuKWeei9/dd899R5dbcdoSl7y18Y8eWjY8=,tag:WYUqqCWRvoY8RBGUJr/qbw==,type:str]
        client_secret: ENC[AES256_GCM,data:vc/6Y3JhvhTiqJft5bPTwPJPdbIKMk5nQ/7N52RORxCK7+ksPdszkVREcoFLowfX+46wMJoF9c7Am3y/uqrH,iv:QuVxTljUBjhR+ZfzTXy8r5BKLvmjPEF3zFkz93GhFiQ=,tag:7eSHosiF10/Ogs+wyoi9jw==,type:str]
  suspend: false
