apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prod/cilium
    repoURL: https://github.com/devusb/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
